---
- name: Run deluge container
  docker_container:
    name: deluge
    image: lsioarmhf/deluge:{{deluge_image_version}}
    volumes:
      - "{{deluge_download_dir}}:/downloads"
      - "{{deluge_config_dir}}:/config"
    restart: yes
    restart_policy: always
    network_mode: host
    env:
      TZ: Hong Kong
      PUID: 1000
      PGID: 1000
