---
- name: Install required packages
  apt:
    name: monit
    state: present
  become: True

- name: Copy monit config
  copy: src=monitrc dest=/etc/monit/monitrc
  become: True
  notify:
    - reload monit

- name: Copy systemd config
  copy: src=monit.service dest=/lib/systemd/system/monit.service
  become: True

- name: Start monit on boot
  systemd:
    name: monit
    state: started
  become: True
