---
- name: Run syncthing container
  docker_container:
    name: syncthing
    image: funkyfuture/rpi-syncthing:{{syncthing_version}}
    ports:
      - "8384:8384"
      - "22000:22000"
      - "21205:21205/udp"
    volumes:
      - "{{syncthing_config_dir}}:/syncthing/config"
      - "{{syncthing_data_dir}}:/syncthing/data"
    restart: yes
    restart_policy: always
    network_mode: host
    env:
      GUI_ADDRESS: "[::]:{{syncthing_public_port}}"
