---
- name: Install required packages
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - rpcbind
    - nfs-kernel-server
  become: True

- name: Copy /etc/exports
  copy:
    src: exports
    dest: /etc/exports
  notify:
    - restart rpcbind
    - restart nfs-kernel-server
  become: True
